### ISSUE TITLE
Version 1.1.0 Development Tracking

### ISSUE THREAD

**Issue by ZZ-Cat** [ZZ-Cat/CRSFforArduino#111]
> [!note]
> There is currently a feature-freeze on CFA.
> No new features shall be added _until after_ v1.1.0 is released.
> Known issues are taking priority in order of security enhancements, followed by bug fixes, and existing code-base feature requests are lower priority.

See [this milestone](../milestone/5) and my [development schedule](https://github.com/users/ZZ-Cat/projects/7) for details.

## The list

The list here is based on my [Development Schedule](https://github.com/users/ZZ-Cat/projects/7), where you can see what I am working on, and what's receiving my priority attention. All items, unless stated otherwise, appear in their respective categories on a first-in-first-out basis, and progress is made on each one in descending order.  
As each item is completed, it is moved to the "Completed" category at the bottom of this list.

### In progress

This is what is actively being worked on.  
Items in this category are in order of priority, where the topmost item is my highest priority and the lowermost item is my lowest priority.

- [ ] Security updates
  - [x] Fix CodeQL errors - This seems to have fixed itself, for some reason.
  - [x] Containerise CFA's development environment.
  - [x] Add cppcheck and clang-tidy checks to my quality control.
  - [ ] Implement [Compile Hardening](https://best.openssf.org/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++) as outlined by the [OpenSSF's](https://openssf.org/about/) [Security Guidelines](https://openssf.org/resources/guides/)
  - [ ] Add a security policy.
  - [ ] Enable private vulnerability reporting.
- [x] Re-organise files-and-folders for easier discoverability.
  - [x] Make a script folder to simplify building, checking, and deploying CFA during the development cycle.

### To-do

This is my "to-do" list, and it contains items that have been triaged, but are still waiting for me to work on.

- [ ] #108
- [ ] #119
- [ ] #125
- [x] #139
- [ ] #140

### On hold

An item in this list means that development on it has temporarily stopped, while I focus on higher priorities.

- [ ] #103
- [ ] #113

### Planned

This is what I have rattling around in my mind, and need to get it out of the æther, and written here before my short-term memory loss gets the better of me. Keep in mind that anything added here may not make it into the upcoming release, and if it doesn't, it may appear in a follow-up release.

- [ ] Update Contribution Guidelines
  - [ ] State _all_ commits MUST be verified
  - [ ] Pull Request guidelines
  - [ ] Condense all guidelines into a concise format, with a list of "key takeaways"
- [ ] Add Pull Request Template
- [ ] Add PlatformIO requirements to Issue Templates
- [ ] New API function: `pulseIn()`
       This could empower developers to integrate CRSF for Arduino into existing projects with minimal (if any) changes to their existing code-base.
- [ ] RP2350 Support

### Completed

This is the stuff what's been completed and will make it into the upcoming Version 1.1.0 release.

- [x] #157
- [x] #156
- [x] #107
- [x] #89
- [x] #117
- [x] #116
- [x] #115
- [x] #112
- [x] #128
- [x] #134

### Stalled

When development on one (or more) items has stalled for more than a month from its last commit, it is listed here.

## Additional

During this time, I ask that you _please_ be patient and understand that I am but _one_ person working on CRSF for Arduino.  
I have had my fair share of contributors as time has marched on, and they are not without my respect. I am very grateful for their efforts, and my contributors have been a huge help in lightening the load for me.

However, 99% of the time I am the _only one_ working on CRSF for Arduino, and as its popularity grows, I need to prioritise my focus in order to preserve my work-life balance, negate burning myself out _and_ to negate myself from being overwhelmed with a perceived "MUST do ALL the things... AT ONCE!!!!1111!!!11!"

If you are able, I encourage you to get involved with my project in the following ways:

- Testing the code base on supported hardware;
- Bug-testing and submitting feedback;
- Pull Requests;

> [!NOTE]
> For Pull Requests, you `MUST` have either GPG or SSH signing enabled _before_ your _first_ commit to your Pull Request's branch. All commits in your Pull Request `MUST` have the green `verified` badge next to them.  
> This is the same reason why you write your signature on an official document - It verifies that it's _you_ that wrote the commit and _not_ someone trying to impersonate you.

**Comment by BadPotato1007** [comment]
So do you have an approximate of when this functionality will be ready? I am planning to use this lib to make a fully diy handset from scratch that can use elrs external modules...

**Comment by ZZ-Cat** [comment]
> So do you have an approximate of when this functionality will be ready?

As my dad used to say: "It will be ready when it's ready." =^/.~=  
Or, as Trappy of Team BlackSheep would occasionally joke: "Two weeks."

For real, though. I don't do the whole "deadline" thing.  
I'd rather get this done right the first time, as opposed to rushing to meet ~~unrealistic~~ deadlines.

It's unrealistic to ask for a specific "due by" date, when the very nature of software development is unpredictable at best and has its fair share of delays and setbacks at worst.

Another thing ya gotta remember is... I'm just a gal what does this in her free time.  
I'm not funded by some big corporation or employed to do this "full-time". I write this stuff on my own terms.
